# Generated by Django 2.2.6 on 2019-10-24 20:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('deeds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=64, unique=True)),
                ('data', models.FileField(upload_to='uploads/data/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])])),
                ('deed_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deeds.DeedType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
