# Generated by Django 2.2.6 on 2019-10-25 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deeds', '0002_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name_plural': 'Data'},
        ),
        migrations.AddField(
            model_name='source',
            name='data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='deeds.Data'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='source',
            unique_together={('data', 'classmark', 'microfilm')},
        ),
    ]
