# Generated by Django 2.2.6 on 2019-10-25 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geonames_place', '0004_change_meta_options_on_country'),
        ('deeds', '0004_load_initial_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['surname', 'name', 'dob']},
        ),
        migrations.AddField(
            model_name='data',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='geonames_place.Place'),
            preserve_default=False,
        ),
    ]
