# Generated by Django 2.2.6 on 2019-10-25 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deeds', '0005_add_field_place_to_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deeds.Profession'),
        ),
    ]
