# Generated by Django 2.2.6 on 2019-10-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deeds', '0006_alter_field_profession_on_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='title',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
