# Generated by Django 2.2.6 on 2019-10-28 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geonames_place', '0004_change_meta_options_on_country'),
        ('deeds', '0008_add_related_name_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deed',
            unique_together={('n', 'date', 'place')},
        ),
    ]
