# Generated by Django 2.2.6 on 2019-10-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deeds', '0009_alter_unique_together_for_deed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name', 'surname', 'age']},
        ),
        migrations.RemoveField(
            model_name='person',
            name='dob',
        ),
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='year_of_birth',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
