# Generated by Django 2.2.6 on 2019-10-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deeds', '0010_alter_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
