# Generated by Django 2.2.6 on 2019-10-30 16:31

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('deeds', '0011_alter_person_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ['title'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='deedtype',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='origintype',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['surname', 'name', 'age']},
        ),
        migrations.AlterModelOptions(
            name='profession',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='profession',
            name='title',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
