# Generated by Django 2.2.6 on 2019-10-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deeds', '0012_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deedtype',
            name='title',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='gender',
            name='title',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='origintype',
            name='title',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='profession',
            name='title',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='title',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
