# Generated by Django 2.2.6 on 2019-10-30 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deeds', '0013_alter_al_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deeds.Gender'),
        ),
    ]
