# Generated by Django 2.2.6 on 2019-10-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deeds', '0015_deed_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='origin',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
