# Generated by Django 2.2.6 on 2019-10-30 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deeds', '0016_origin_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='origin',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='originated_from', to='deeds.Person'),
        ),
        migrations.AlterField(
            model_name='origin',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_of', to='geonames_place.Place'),
        ),
    ]
