# Generated by Django 2.2.6 on 2019-11-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deeds', '0019_rename_field_year_of_birth_on_person_to_birth_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='origin',
            name='is_date_computed',
            field=models.BooleanField(default=False, help_text='Wether the date was computed using the person birth date and the date of the deed'),
            preserve_default=False,
        ),
    ]
